name: squirrel

dependencies:
  - base
  - bytestring
  - data-default
  - lens
  - mtl
  - template-haskell
  - text
  - tree-sitter
  - pretty

default-extensions:
  - LambdaCase
  - BlockArguments
  - OverloadedStrings
  - GeneralisedNewtypeDeriving
  - DerivingStrategies
  - DerivingVia
  - FlexibleInstances
  - NamedFieldPuns
  - BangPatterns
  - ScopedTypeVariables
  - QuasiQuotes
  - TemplateHaskell

ghc-options: -freverse-errors -Wall -threaded

library:
  source-dirs:
    - src/

  include-dirs:
    - vendor

  c-sources:
    - vendor/parser.c

executables:
  squirrel:
    dependencies:
      - base
      - stm
      - haskell-lsp
      - squirrel
      - hslogger
      - interpolate

    main: Main.hs

    source-dirs:
      - app/
