name: ligo-squirrel

dependencies:
  - base
  - bytestring
  - containers
  - data-default
  - fastsum
  - mtl
  - pretty
  - template-haskell
  - text
  - tree-sitter

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralisedNewtypeDeriving
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - QuasiQuotes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns

ghc-options: -freverse-errors -Wall -threaded

library:
  source-dirs:
    - src/

  include-dirs:
    - vendor

  c-sources:
    - vendor/parser.c

executables:
  squirrel:
    dependencies:
      - haskell-lsp
      - hslogger
      - interpolate
      - lens
      - ligo-squirrel
      - stm

    main: Main.hs

    source-dirs:
      - app/
